### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by thim81** [LKDevelopment/laravel-uptime-monitor-cachet-integration#6]
In the readme, there is referal to the documentation:
http://lk-development.de/docs/laravel-uptime-monitor-cachet-integration-v1/

But it's broken?

**Comment by LKaemmerling** [comment]
Thank you!The broken link is fixed now.

**Comment by PieterHollevoet** [comment]
Is the link to the documentation broken again ?

**Comment by LKaemmerling** [comment]
Yeah looks like. But currently i don't have the time to maintain this package.
